sudo: required

language: node_js

node_js:
  - "8"

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm

before_script:
  - npm run init

script:
  - npm run ci
