language: node_js

node_js:
  - "8"

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm

script:
  - lerna run lint
  - lerna run build
  - lerna run test
